# Generated by Django 2.2 on 2021-02-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normal', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normal.Customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normal.Product'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='normal.Order'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='normal.Customer'),
        ),
    ]
