# Generated by Django 2.2 on 2021-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal', '0004_auto_20210217_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
