# Generated by Django 2.2 on 2021-02-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal', '0005_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
